#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0

RUN mkdir /app
WORKDIR /app

COPY ./bin/Release/net6.0/publish ./

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "AzWebApp.dll"]